export const INITIAL_USER_GEMS = 0;

export const DEFAULT_AVATAR_URL = "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80";

export const MOCK_FRAMES = [
  // =========================================================================
  // 🟢 LEVEL 1: COMMON (4 KHUNG ĐỘC ĐÁO - GIÁ 50 - 120 GEMS)
  // =========================================================================
  {
    id: 1,
    frameKey: "common-bronze-octagon",
    name: "Khiên Bát Giác Đồng",
    rarity: "Common",
    gemCost: 50,
    status: "locked",
    avatarBg: "#FDF6E2",
    frameColor: "#CD7F32",
    secondaryColor: "#8B5A2B",
    accentColor: "#D2691E",
    borderColor: "#A0522D",
    glowColor: "rgba(205, 127, 50, 0.2)",
    iconSymbol: "🛡️",
    avatarInitials: "BO",
    description: "Cấu trúc viền bát giác đúc bằng đồng thau với 8 chốt nịt đính ở góc."
  },
  {
    id: 2,
    frameKey: "common-iron-cog",
    name: "Bánh Răng Sắt Cổ",
    rarity: "Common",
    gemCost: 75,
    status: "locked",
    avatarBg: "#F1F5F9",
    frameColor: "#64748B",
    secondaryColor: "#475569",
    accentColor: "#334155",
    borderColor: "#1E293B",
    glowColor: "rgba(100, 116, 139, 0.2)",
    iconSymbol: "⚙️",
    avatarInitials: "IC",
    description: "Cấu trúc bánh răng cơ khí sắt rèn có các khớp răng cưa chạy quanh viền."
  },
  {
    id: 3,
    frameKey: "common-stone-slab",
    name: "Bảng Đá Cổ Núi",
    rarity: "Common",
    gemCost: 90,
    status: "locked",
    avatarBg: "#E2E8F0",
    frameColor: "#94A3B8",
    secondaryColor: "#64748B",
    accentColor: "#475569",
    borderColor: "#334155",
    glowColor: "rgba(148, 163, 184, 0.2)",
    iconSymbol: "🪨",
    avatarInitials: "SS",
    description: "Khung đá thô vuông bo tròn góc chạm vết nứt núi đá huyền bí."
  },
  {
    id: 4,
    frameKey: "common-wood-oak",
    name: "Vòng Gỗ Sồi Rừng",
    rarity: "Common",
    gemCost: 120,
    status: "locked",
    avatarBg: "#FEF3C7",
    frameColor: "#854D0E",
    secondaryColor: "#A16207",
    accentColor: "#713F12",
    borderColor: "#543310",
    glowColor: "rgba(133, 77, 14, 0.2)",
    iconSymbol: "🪵",
    avatarInitials: "WO",
    description: "Khung gỗ sồi nguyên khối khắc vân uốn và gờ lá rừng ở 2 bên."
  },

  // =========================================================================
  // 🔵 LEVEL 2: RARE (3 KHUNG ĐỘC ĐÁO - GIÁ 250 - 480 GEMS)
  // =========================================================================
  {
    id: 5,
    frameKey: "rare-silver-swords",
    name: "Hiệp Sĩ Kiếm Bạc",
    rarity: "Rare",
    gemCost: 250,
    status: "locked",
    avatarBg: "#F0F9FF",
    frameColor: "#E2E8F0",
    secondaryColor: "#38BDF8",
    accentColor: "#0284C7",
    borderColor: "#0369A1",
    glowColor: "rgba(56, 189, 248, 0.4)",
    iconSymbol: "⚔️",
    avatarInitials: "SS",
    description: "Cấu trúc viền bạc chạm trổ khiên Hiệp sĩ với 2 thanh kiếm chéo đính ở chân khung."
  },
  {
    id: 6,
    frameKey: "rare-frost-spikes",
    name: "Chông Băng Bão Tuyết",
    rarity: "Rare",
    gemCost: 350,
    status: "locked",
    avatarBg: "#F0F9FF",
    frameColor: "#0284C7",
    secondaryColor: "#38BDF8",
    accentColor: "#0369A1",
    borderColor: "#1E3A8A",
    glowColor: "rgba(2, 132, 199, 0.5)",
    iconSymbol: "❄️",
    avatarInitials: "FS",
    description: "Các chông băng sắc nhọn đâm ra từ 4 phía kèm bông hoa tuyết lục giác trên đỉnh."
  },
  {
    id: 7,
    frameKey: "rare-sakura-heart",
    name: "Trái Tim Anh Đào",
    rarity: "Rare",
    gemCost: 480,
    status: "locked",
    avatarBg: "#FDF2F8",
    frameColor: "#EC4899",
    secondaryColor: "#F472B6",
    accentColor: "#DB2777",
    borderColor: "#9D174D",
    glowColor: "rgba(236, 72, 153, 0.5)",
    iconSymbol: "🌸",
    avatarInitials: "SH",
    description: "Vòng dây hoa anh đào kết hình trái tim uốn lượn kèm 5 cánh hoa rơi 3D ở góc dưới."
  },

  // =========================================================================
  // 🟣 LEVEL 3: LEGENDARY (2 KHUNG ĐỘC ĐÁO - GIÁ TĂNG GẤP ĐÔI: 2400 - 4000 GEMS)
  // =========================================================================
  {
    id: 8,
    frameKey: "legendary-ruby-warlock",
    name: "Pháp Sư Hồng Ngọc",
    rarity: "Legendary",
    gemCost: 2400, // Tăng gấp đôi từ 1200 -> 2400
    status: "locked",
    avatarBg: "#FFF1F2",
    frameColor: "#F43F5E",
    secondaryColor: "#FB7185",
    accentColor: "#E11D48",
    borderColor: "#9F1239",
    glowColor: "rgba(244, 63, 94, 0.65)",
    iconSymbol: "🔮",
    avatarInitials: "RW",
    description: "Vương miện 3 đỉnh ngọc đỏ rực kết hợp ma pháp tam giác ngược và 3 quả cầu năng lượng lơ lửng."
  },
  {
    id: 9,
    frameKey: "legendary-cyber-wings",
    name: "Cánh Giáp Cyberpunk",
    rarity: "Legendary",
    gemCost: 4000, // Tăng gấp đôi từ 2000 -> 4000
    status: "locked",
    avatarBg: "#ECFEFF",
    frameColor: "#06B6D4",
    secondaryColor: "#EC4899",
    accentColor: "#3B82F6",
    borderColor: "#0891B2",
    glowColor: "rgba(6, 182, 212, 0.75)",
    iconSymbol: "👾",
    avatarInitials: "CW",
    description: "Cụm cánh giáp Cyberpunk đa tầng nhọn hoắt 2 bên hông kèm mũ giáp sừng chéo đỉnh."
  },

  // =========================================================================
  // 🟡 LEVEL 4: MYTHIC (1 KHUNG SIÊU CẤP DUY NHẤT - GIÁ TĂNG GẤP ĐÔI: 9000 GEMS)
  // =========================================================================
  {
    id: 10,
    frameKey: "mythic-god-king-dragon",
    name: "Nhà Vô Địch Tuyệt Đối (Thần Vương)",
    rarity: "Mythic",
    gemCost: 9000, // Tăng gấp đôi từ 4500 -> 9000
    status: "locked",
    avatarBg: "#FEF3C7",
    frameColor: "#F59E0B",
    secondaryColor: "#FCD34D",
    accentColor: "#D97706",
    borderColor: "#78350F",
    glowColor: "rgba(245, 158, 11, 0.95)",
    iconSymbol: "👑",
    avatarInitials: "GK",
    description: "🏆 KHUNG HOÀNG GIA THẦN THOẠI DUY NHẤT: Đôi cánh Rồng Thần 3D uốn lượn toàn thân, Vương miện Thần Vương 5 đỉnh nạm ngọc Ruby/Diamond, Khiên Rồng phong ấn và các vì sao tự động xoay lấp lánh!"
  }
];

export const MOCK_ACHIEVEMENTS = [
  {
    id: 'ach-1',
    code: 'VOCAB_100',
    title: 'Học 100 Từ Vựng',
    description: 'Trở thành kho từ vựng di động với 100 từ tiếng Anh ghi nhớ sâu.',
    requirementText: '💡 Cách đạt: Hoàn thành và vượt qua bài kiểm tra của 100 từ vựng khác nhau trong các bài học.',
    category: 'vocab',
    progressCurrent: 0,
    progressTarget: 100,
    rewardGems: 100,
    rewardXp: 250,
    badgeIcon: '📚',
    badgeColor: '#FEF08A',
    badgeBorderColor: '#EAB308',
    badgeGlowColor: 'rgba(234, 179, 8, 0.4)',
    status: 'locked',
  },
  {
    id: 'ach-2',
    code: 'STREAK_7',
    title: 'Đạt Streak 7 Ngày',
    description: 'Xây dựng thói quen học tập bền bỉ không bỏ lỡ ngày nào.',
    requirementText: '💡 Cách đạt: Duy trì chuỗi học liên tục mỗi ngày trong 7 ngày liên tiếp.',
    category: 'streak',
    progressCurrent: 0,
    progressTarget: 7,
    rewardGems: 150,
    rewardXp: 350,
    badgeIcon: '🔥',
    badgeColor: '#FFEDD5',
    badgeBorderColor: '#F97316',
    badgeGlowColor: 'rgba(249, 115, 22, 0.45)',
    status: 'locked',
  },
  {
    id: 'ach-3',
    code: 'NIGHT_OWL',
    title: 'Cú Đêm Học Tập',
    description: 'Chăm chỉ học tập khi cả thế giới đang chìm vào giấc ngủ.',
    requirementText: '💡 Cách đạt: Hoàn thành ít nhất 1 bài học trọn vẹn trong khung giờ đêm từ 22:00 đến 04:00 sáng.',
    category: 'time',
    progressCurrent: 0,
    progressTarget: 1,
    rewardGems: 80,
    rewardXp: 180,
    badgeIcon: '🌙',
    badgeColor: '#E9D5FF',
    badgeBorderColor: '#8B5CF6',
    badgeGlowColor: 'rgba(139, 92, 246, 0.45)',
    status: 'locked',
  },
  {
    id: 'ach-4',
    code: 'SPEED_DEMON',
    title: 'Tốc Độ Ánh Sáng',
    description: 'Phản xạ nhanh như chớp với vốn từ vựng chuẩn xác.',
    requirementText: '💡 Cách đạt: Hoàn thành 1 bài kiểm tra 10 câu hỏi với điểm tuyệt đối 100% trong thời gian dưới 90 giây.',
    category: 'study',
    progressCurrent: 0,
    progressTarget: 1,
    rewardGems: 120,
    rewardXp: 280,
    badgeIcon: '⚡',
    badgeColor: '#CFFAFE',
    badgeBorderColor: '#06B6D4',
    badgeGlowColor: 'rgba(6, 182, 212, 0.4)',
    status: 'locked',
  },
  {
    id: 'ach-5',
    code: 'GRAMMAR_GURU',
    title: 'Bậc Thầy Ngữ Pháp',
    description: 'Nắm vững các cấu trúc thì và câu phức trong tiếng Anh.',
    requirementText: '💡 Cách đạt: Vượt qua 20 bài tập thử thách Ngữ Pháp nâng cao không mắc lỗi nào.',
    category: 'grammar',
    progressCurrent: 0,
    progressTarget: 20,
    rewardGems: 200,
    rewardXp: 450,
    badgeIcon: '📜',
    badgeColor: '#E0E7FF',
    badgeBorderColor: '#6366F1',
    badgeGlowColor: 'rgba(99, 102, 241, 0.4)',
    status: 'locked',
  },
  {
    id: 'ach-6',
    code: 'SPEAKING_PRO',
    title: 'Phát Âm Chuẩn CHỦN',
    description: 'Luyện giọng đọc tiếng Anh như người bản xứ.',
    requirementText: '💡 Cách đạt: Đạt điểm đánh giá giọng nói AI từ 90% trở lên cho 30 câu đàm thoại.',
    category: 'speaking',
    progressCurrent: 0,
    progressTarget: 30,
    rewardGems: 180,
    rewardXp: 400,
    badgeIcon: '🎙️',
    badgeColor: '#FCE7F3',
    badgeBorderColor: '#EC4899',
    badgeGlowColor: 'rgba(236, 72, 153, 0.45)',
    status: 'locked',
  },
  {
    id: 'ach-7',
    code: 'TOP_LEAGUE',
    title: 'Vinh Quang Bảng Xếp Hạng',
    description: 'Khẳng định vị thế dẫn đầu trong cộng đồng người học.',
    requirementText: '💡 Cách đạt: Kết thúc tuần ở vị trí Top 3 trên Bảng Xếp Hạng Giải Vàng (Gold League) trở lên.',
    category: 'streak',
    progressCurrent: 0,
    progressTarget: 1,
    rewardGems: 300,
    rewardXp: 600,
    badgeIcon: '🏆',
    badgeColor: '#FEF3C7',
    badgeBorderColor: '#D97706',
    badgeGlowColor: 'rgba(217, 119, 6, 0.5)',
    status: 'locked',
  },
  {
    id: 'ach-8',
    code: 'EARLY_BIRD',
    title: 'Sơn Dụ Bình Minh',
    description: 'Năng lượng dồi dào chào đón ngày mới bằng bài học Tiếng Anh.',
    requirementText: '💡 Cách đạt: Hoàn thành bài học đầu tiên trong ngày vào khung giờ sớm từ 05:00 đến 07:00 sáng.',
    category: 'time',
    progressCurrent: 0,
    progressTarget: 1,
    rewardGems: 90,
    rewardXp: 200,
    badgeIcon: '🌅',
    badgeColor: '#FFEDD5',
    badgeBorderColor: '#EA580C',
    badgeGlowColor: 'rgba(234, 88, 12, 0.4)',
    status: 'locked',
  }
];
