import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fcf9f9",
  },
  headerBackground: {
    paddingTop: 40,
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    backgroundColor: '#9B2C2C',
    position: 'relative',
    overflow: 'hidden',
  },
  headerDecorativeCircle: {
    position: 'absolute',
    top: -50,
    right: -50,
    width: 220,
    height: 220,
    borderRadius: 175,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  progressBarContainer: {
    flex: 1,
    height: 6,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 3,
    marginHorizontal: 15,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#F45B69",
    borderRadius: 3,
  },
  progressText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
    opacity: 0.8,
  },
  phaseBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  phaseBadgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 32,
    marginHorizontal: 20,
    flex: 1,
    marginBottom: 10,
    marginTop: 20,
    overflow: "hidden",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  quizBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff8e1',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  quizBadgeText: {
    color: '#f57f17',
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 6,
    textTransform: 'uppercase',
  },
  quizQuestion: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1a1a1a",
    marginBottom: 20,
  },
  quizOption: {
    backgroundColor: "#fff",
    padding: 18,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#f0f0f0",
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  optionIndex: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  optionIndexText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#999",
  },
  optionText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#444",
    flex: 1,
  },
  optionSelected: {
    borderColor: "#F45B69",
    backgroundColor: "rgba(244, 91, 105, 0.05)",
  },
  optionCorrect: {
    borderColor: "#10b981",
    backgroundColor: "#ecfdf5",
  },
  optionWrong: {
    borderColor: "#ef4444",
    backgroundColor: "#fef2f2",
  },
  fillContainer: {
    backgroundColor: "#f9f9f9",
    padding: 20,
    borderRadius: 24,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: "#eee",
  },
  fillText: {
    fontSize: 18,
    color: "#333",
    lineHeight: 28,
    textAlign: "center",
  },
});
