import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fcf9f9", 
  },
  headerBackground: {
    paddingTop: 40,
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    backgroundColor: '#9B2C2C', // Fallback
    position: 'relative',
    overflow: 'hidden',
  },
  headerDecorativeCircle: {
    position: 'absolute',
    top: -50,
    right: -50,
    width: 220,
    height: 220,
    borderRadius: 175,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  progressBarContainer: {
    flex: 1,
    height: 6,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 3,
    marginHorizontal: 15,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#F45B69",
    borderRadius: 3,
  },
  progressText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
    opacity: 0.8,
  },
  phaseBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  phaseBadgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  
  // Progress Dots
  dotsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 20,
    gap: 8,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  dotActive: {
    backgroundColor: "#F45B69",
    width: 20,
  },
  dotDone: {
    backgroundColor: "rgba(244, 91, 105, 0.4)",
  },

  // Card styles
  card: {
    backgroundColor: "#fff",
    borderRadius: 32,
    marginHorizontal: 20,
    flex: 1,
    marginBottom: 10,
    marginTop: 20,
    overflow: "hidden",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  cardImageContainer: {
    height: 240,
    width: "100%",
    backgroundColor: "#F45B69",
  },
  cardImage: {
    width: "100%",
    height: "100%",
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.1)",
  },
  audioButtonOverlay: {
    position: "absolute",
    right: 20,
    bottom: 20,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  cardContent: {
    padding: 24,
    flex: 1,
  },
  noImageTopBar: {
    height: 120,
    width: "100%",
    backgroundColor: "#9B2C2C",
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    padding: 24,
    position: 'relative',
    overflow: 'hidden',
  },
  noImageGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  typeBadgeGray: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  typeTextGray: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  audioButtonSolid: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#e53935",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#e53935",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  typeBadge: {
    backgroundColor: "rgba(244, 91, 105, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: "flex-start",
    marginBottom: 12,
  },
  typeText: {
    color: "#F45B69",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  wordTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: "#1a1a1a",
    marginBottom: 4,
  },
  phonetic: {
    fontSize: 18,
    color: "#666",
    fontFamily: "System",
    marginBottom: 20,
  },
  definitionContainer: {
    marginBottom: 20,
  },
  definitionEn: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    lineHeight: 26,
    marginBottom: 4,
  },
  definitionVn: {
    fontSize: 14,
    color: "#888",
    fontStyle: "italic",
  },
  exampleContainer: {
    backgroundColor: "rgba(244, 91, 105, 0.05)",
    padding: 16,
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#F45B69",
    marginBottom: 20,
  },
  exampleEn: {
    fontSize: 15,
    color: "#444",
    lineHeight: 22,
    marginBottom: 6,
  },
  exampleVn: {
    fontSize: 13,
    color: "#999",
  },
  highlight: {
    color: "#F45B69",
    fontWeight: "700",
  },
  synonymSection: {
    marginTop: 24,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  synonymTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#bbb",
    marginBottom: 10,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  synonymContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  synonymChip: {
    backgroundColor: "#f5f5f5",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#eee",
  },
  synonymText: {
    fontSize: 13,
    color: "#666",
    fontWeight: "600",
  },

  // Footer Buttons
  footerContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    paddingTop: 10,
    backgroundColor: '#fcf9f9',
  },
  quitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    backgroundColor: 'rgba(244, 91, 105, 0.1)',
    borderRadius: 20,
    marginBottom: 12,
  },
  quitButtonText: {
    color: '#e53935',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  footer: {
    flexDirection: "row",
    gap: 12,
  },
  buttonSecondary: {
    flex: 1,
    height: 56,
    backgroundColor: "#f0eaeb",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  buttonPrimary: {
    flex: 1.5,
    height: 56,
    backgroundColor: "#9B2C2C",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  buttonTextPrimary: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
    marginHorizontal: 8,
  },
  buttonTextSecondary: {
    color: "#666",
    fontSize: 16,
    fontWeight: "700",
  },

  // Quiz Styles
  quizTabBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 16,
    marginTop: 10,
    gap: 10,
  },
  quizTab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    backgroundColor: '#fff',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  quizTabActive: {
    borderColor: '#ffcdd2',
    backgroundColor: '#ffebee',
  },
  quizTabText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#9e9e9e',
  },
  quizTabTextActive: {
    color: '#e53935',
  },
  quizBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff8e1',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  quizBadgeText: {
    color: '#f57f17',
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 6,
    textTransform: 'uppercase',
  },
  quizContainer: {
    padding: 24,
  },
  quizQuestion: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1a1a1a",
    marginBottom: 20,
  },
  quizQuestionHighlight: {
    color: "#e53935",
  },
  quizOption: {
    backgroundColor: "#fff",
    padding: 18,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#f0f0f0",
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  optionIndex: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  optionIndexText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#999",
  },
  optionText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#444",
    flex: 1,
  },
  optionSelected: {
    borderColor: "#F45B69",
    backgroundColor: "rgba(244, 91, 105, 0.05)",
  },
  optionCorrect: {
    borderColor: "#10b981",
    backgroundColor: "#ecfdf5",
  },
  optionWrong: {
    borderColor: "#ef4444",
    backgroundColor: "#fef2f2",
  },
  
  // Fill in the blank
  fillContainer: {
    backgroundColor: "#f9f9f9",
    padding: 20,
    borderRadius: 24,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: "#eee",
  },
  fillText: {
    fontSize: 18,
    color: "#333",
    lineHeight: 28,
    textAlign: "center",
  },
  fillBlank: {
    borderBottomWidth: 2,
    borderBottomColor: "#F45B69",
    paddingHorizontal: 10,
    minWidth: 80,
    textAlign: "center",
    fontWeight: "800",
    color: "#F45B69",
  },
  wordBank: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
    marginTop: 10,
  },
  wordChip: {
    backgroundColor: "#f5f5f5",
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  wordChipText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#555",
  },
  wordChipUsed: {
    opacity: 0.3,
    backgroundColor: "#f5f5f5",
  },

  // Match
  matchRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 10,
  },
  matchColumn: {
    flex: 1,
    gap: 10,
  },
  matchHeader: {
    fontSize: 12,
    fontWeight: "800",
    color: "#999",
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  matchCard: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#f0f0f0",
    minHeight: 80,
    justifyContent: "center",
    alignItems: "center",
  },
  matchText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#444",
    textAlign: "center",
  },
  matchSelected: {
    borderColor: "#F45B69",
    backgroundColor: "rgba(244, 91, 105, 0.05)",
  },
  matchMatched: {
    borderColor: "#10b981",
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    opacity: 0.5,
  },

  // Writing Enhanced
  writingPrompt: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1a1a1a",
    marginBottom: 16,
    textAlign: "left",
  },
  keywordSection: {
    marginBottom: 20,
  },
  keywordTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#999",
    marginBottom: 10,
    textTransform: "uppercase",
  },
  keywordChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  keywordChip: {
    backgroundColor: "rgba(155, 44, 44, 0.08)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(155, 44, 44, 0.2)",
  },
  keywordChipText: {
    fontSize: 14,
    color: "#9B2C2C",
    fontWeight: "700",
  },
  writingInput: {
    backgroundColor: "#fcfcfc",
    borderRadius: 20,
    padding: 20,
    fontSize: 16,
    color: "#333",
    textAlignVertical: "top",
    borderWidth: 1.5,
    borderColor: "#f0f0f0",
    minHeight: 180,
    marginBottom: 20,
  },

  // AI Feedback
  feedbackContainer: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: "#eee",
  },
  feedbackTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1a1a1a",
    marginBottom: 15,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff8e1',
    padding: 16,
    borderRadius: 16,
    marginBottom: 20,
  },
  scoreValue: {
    fontSize: 32,
    fontWeight: '900',
    color: '#ffa000',
    marginRight: 12,
  },
  scoreLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#f57f17',
    textTransform: 'uppercase',
  },
  improvedBox: {
    backgroundColor: "#f0f4f8",
    padding: 16,
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#2196f3",
    marginBottom: 20,
  },
  improvedTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#2196f3",
    marginBottom: 6,
    textTransform: "uppercase",
  },
  improvedText: {
    fontSize: 15,
    color: "#334e68",
    lineHeight: 22,
    fontWeight: "600",
  },
  keywordAnalysisItem: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#f0f0f0',
    alignItems: 'flex-start',
  },
  analysisContent: {
    flex: 1,
    marginLeft: 10,
  },
  analysisWord: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 2,
  },
  analysisReason: {
    fontSize: 13,
    color: '#666',
    lineHeight: 18,
  },

  // Result
  resultContainer: {
    flex: 1,
    padding: 30,
    alignItems: "center",
    justifyContent: 'space-between',
  },
  resultCloseButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  resultHeader: {
    width: '100%',
    alignItems: 'center',
    marginTop: 80,
  },
  trophyContainer: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  congratsTitle: {
    fontSize: 32,
    fontWeight: "900",
    color: "#fff",
    marginBottom: 12,
    textAlign: "center",
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  congratsText: {
    fontSize: 16,
    color: "rgba(255, 255, 255, 0.85)",
    textAlign: "center",
    lineHeight: 24,
    paddingHorizontal: 20,
  },
  xpCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 24,
    padding: 24,
    width: '100%',
    alignItems: 'center',
    marginBottom: 40,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  xpBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 215, 0, 0.25)",
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: "rgba(255, 215, 0, 0.4)",
  },
  xpText: {
    fontSize: 36,
    fontWeight: "900",
    color: "#FFD700",
    marginLeft: 12,
  },
  resultFooter: {
    width: '100%',
    paddingBottom: 20,
  },
  buttonPrimaryResult: {
    height: 64,
    backgroundColor: "#fff",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  buttonTextPrimaryResult: {
    color: "#9B2C2C",
    fontSize: 18,
    fontWeight: "800",
    marginHorizontal: 12,
  },
});

export default styles;
